"""
Legal/compliance guardrails — enforced in code, not just documentation.

The spec is explicit about this product's one hard legal line: "The product
explains what it found and why it might matter — it does not tell a client
'you are compliant' or 'you are not compliant.' That's a legal conclusion;
this is a monitoring tool, not a law firm." Saying otherwise, even once, in
a client-facing WhatsApp alert or an auto-drafted notice paragraph, is the
kind of thing that turns a monitoring tool into something that looks like
unauthorized legal advice.

Every string that reaches a client (WhatsApp alert text, drafted notice
paragraphs, drafted inventory rows) is built from a small number of fixed
templates in app/agents/notifier.py — those are safe by construction and
tests/test_guardrails.py fuzzes them across every severity/type/relevance
combination to prove it. The one place client-facing text is NOT
fully fixed-template is the classifier's `detail` field when the real
Gemini backend is in use: it's free-text generated by an LLM prompted to
write "a short human-readable description," and nothing stops a model from
occasionally phrasing that as a compliance conclusion
("you are not DPDP compliant because..."). contains_compliance_conclusion()
below is what app/agents/classifier.py runs against every Gemini-generated
`detail` string before it can flow into an alert.
"""
from __future__ import annotations

import re

# Deliberately narrow and specific rather than broad keyword-banning (e.g.
# banning the bare word "compliant" would also block perfectly legitimate
# text like "confirm this is covered by the consent banner" or dashboard
# copy describing what the product does NOT do). Each pattern targets an
# actual conclusory claim about compliance status/legality, not the topic
# of compliance in general.
_BANNED_PATTERNS: list[tuple[re.Pattern, str]] = [
    (re.compile(r"\byou\s+are\s+(fully\s+|now\s+)?(dpdp[- ]?)?compliant\b", re.I),
     "asserts the client IS compliant"),
    (re.compile(r"\b(is|are|this)\s+(fully\s+|now\s+)?(dpdp[- ]?)?compliant\s+with\b", re.I),
     "asserts something IS compliant with a law/standard"),
    (re.compile(r"\bnot\s+(dpdp[- ]?)?compliant\b", re.I),
     "asserts non-compliance"),
    (re.compile(r"\bnon[- ]compliant\b", re.I),
     "asserts non-compliance"),
    (re.compile(r"\bin\s+violation\s+of\b", re.I),
     "asserts a legal violation"),
    (re.compile(r"\bviolat(e|es|ed|ing|ion)\s+(the\s+)?dpdp\b", re.I),
     "asserts a DPDP violation"),
    (re.compile(r"\bin\s+breach\s+of\b", re.I),
     "asserts a legal breach"),
    (re.compile(r"\bis\s+illegal\b", re.I),
     "asserts illegality"),
    (re.compile(r"\byou\s+(must|are\s+legally\s+required\s+to|are\s+obligated\s+to)\b", re.I),
     "issues a legal directive/obligation, not a finding"),
    (re.compile(r"\bguaranteed?\s+to\s+(pass|comply|be\s+compliant)\b", re.I),
     "asserts a compliance guarantee"),
]


def contains_compliance_conclusion(text: str) -> str | None:
    """Returns a short description of the first banned pattern matched, or
    None if the text is clean. Used both as a runtime guardrail (classifier)
    and as the assertion in tests/test_guardrails.py."""
    if not text:
        return None
    for pattern, description in _BANNED_PATTERNS:
        if pattern.search(text):
            return description
    return None
